/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface StencilSlotBugPoc {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLStencilSlotBugPocElement extends Components.StencilSlotBugPoc, HTMLStencilElement {
    }
    var HTMLStencilSlotBugPocElement: {
        prototype: HTMLStencilSlotBugPocElement;
        new (): HTMLStencilSlotBugPocElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "stencil-slot-bug-poc": HTMLStencilSlotBugPocElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface StencilSlotBugPoc {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "stencil-slot-bug-poc": StencilSlotBugPoc;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "stencil-slot-bug-poc": LocalJSX.StencilSlotBugPoc & JSXBase.HTMLAttributes<HTMLStencilSlotBugPocElement>;
        }
    }
}
